name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-without-build-cache:
    runs-on: blacksmith
    name: Build without build cache

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: useblacksmith/setup-java@v5
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        mvn-build-cache: true

    - name: Install Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.9'

    - name: Build with Maven
      run: mvn -B install

    - name: Test with Maven
      run: mvn -B test

  build-with-build-cache:
    runs-on: blacksmith
    name: Build with build cache

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: useblacksmith/setup-java@v5
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    - name: Install Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.9'

    - name: Mount Maven build cache
      uses: useblacksmith/stickydisk@v1
      with:
        key: maven-build-cache
        path: ~/.m2/build-cache

    - name: Build with Maven
      run: mvn -B clean install

    - name: Test with Maven
      run: mvn -B test 
